import './globals.css';

import type { Metadata } from 'next';

import { NavBar, NavBarLink } from '@/components/ui/NavBar';

const navBarLinks: NavBarLink[] = [
  {
    name: 'home',
    href: '/',
  },
  {
    name: 'about',
    href: '/about',
  },
  {
    name: 'projects',
    href: '/projects',
  },
  {
    name: 'contact',
    href: '#contact',
  },
];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-light text-dark">
        <NavBar links={navBarLinks} />
        {children}
      </body>
    </html>
  );
}
