name: Unlighthouse Audit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Unlighthouse-Audit:
    runs-on: ubuntu-latest
    environment:
      name: Insights
      url: https://personal-site-insights.vercel.app

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install Unlighthouse CLI
        run: npm install --global @unlighthouse/cli

      - name: Run Unlighthouse Audit
        run: unlighthouse-ci --site https://personal-site-842u.vercel.app --build-static

      - name: Push To Static Audit Repo
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:842u/personal-site-insights.git
          BRANCH: main
          FOLDER: .unlighthouse
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 842u_BOT
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/23544888?v=4
        uses: Ilshidur/action-discord@master
        with:
          args: |
            New AUDIT for {{ EVENT_PAYLOAD.repository.full_name }}
            https://personal-site-insights.vercel.app
